config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index,:show]
  resources :items
  root to: 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    @item.save
    redirect_to :action => :index
  end

  def show
    @item = Item.find(params[:id])
    @user = @item.user
  end

  def destroy
    item = Item.find(params[:id])
    item.delete
    redirect_to root_path
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  private
  
  def item_params
    params.require(:item).permit(:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<h1>画像一覧</h1>
<% if user_signed_in? %>
  <% @items.each do |item| %>
    <hr>
    <%= link_to item.user, item_path(item.id)%>さんが投稿
    <p><%= image_tag item.image_url(:thumb) %></p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1>画像詳細</h1>
<p><%= image_tag @item.image_url(:thumb) %></p>
<p><%= link_to '削除', item_path(@item.id), method: :delete, class: 'btn btn-primary'%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp0109</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">NishikiApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "トップ", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to '投稿画面へ', new_item_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'マイページへ', user_path(current_user.id), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: 'post', class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "新規登録", new_user_registration_path, class: 'post', class: "nav-link" %>
        </li>
      <% end %>
    </ul>
</nav>

app/views/users/index.html.erb
登録完了

app/views/users/show.html.erb
<h2><span>email: </span><%= @user.email %></h2>
<hr>
<p>投稿した画像</p>
<% @items.each do |item| %>
  <p><%= image_tag item.image_url(:thumb) %></p>
<% end %>